# Generated by Django 5.1.6 on 2025-10-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "00012_alter_cart_cart_code"),
        ("apiApp", "0014_rename_checkout_id_order_stripe_checkout_id"),
    ]

    operations = []
